### ISSUE TITLE
Prepare Test Data 

### ISSUE THREAD

**Issue by Buwujiu** [Pan-Canadian-Genome-Library/data-dictionary#2]
need testing data that match the PCGL data dictionary for Leo to demo. Test data should be in TSV files. Ask bioinfo.

**Comment by guanqiaofeng** [comment]
Test data:
https://drive.google.com/drive/folders/1j1TsCYXA3ehKAXnQnhLbHHHUpxsQhxcx

TEST_PRO project will pass all the validation
TEST_ERR project will show errors while validated against our JSON shema. Details are in readme.txt
python validation script (validate.py) is also provided.

**Comment by Buwujiu** [comment]
Guangqiao to add test data to pcgl dictionary repo as a separate folder.

**Comment by guanqiaofeng** [comment]
PR for review https://github.com/Pan-Canadian-Genome-Library/data-dictionary/pull/3

**Comment by Buwujiu** [comment]
Test data is merged into main branch, closing.
