### ISSUE TITLE
Update dictionary with conditional restrictions

### ISSUE THREAD

**Issue by edsu7** [Pan-Canadian-Genome-Library/data-dictionary#5]
- current implementation is missing conditional restrictions
- in ARGO, lectern managed this via external scripts
- as an effort to improve functionality : https://github.com/overture-stack/lectern/pull/198
- following lectern merge, dictionary will be updated to reflect changes.

Will need to break down this task further into en epic. It does not block the submission API. 
As we are not accepting data  soon, this task is not urgent, but we need to finish it for dictionary validation to work properly.

**Comment by edsu7** [comment]
Awaiting lectern release:
https://github.com/overture-stack/lectern/pull/198

**Comment by Buwujiu** [comment]
Edmund is waiting for Jon to finish some code changes in Lectern before proceeding on this task. Will have to make a lectern release in PCGL to reflect changes.

**Comment by Buwujiu** [comment]
Moved ticket to Lectern issue - https://github.com/overture-stack/lectern/issues/199. Closing.
